## Introduction
Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones. 

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage. 


Therefore if we can determine if the first stage will land, we can determine the cost of a launch. 

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

 <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
conn = sqlite3.connect("my_data1.db")

In [3]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", conn, if_exists='replace', index=False,method="multi")

101

**Note:This below code is added to remove blank rows from table**

In [4]:
pd.read_sql("""
SELECT * FROM SPACEXTBL
WHERE DATE IS NOT NULL;
""",conn)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
...,...,...,...,...,...,...,...,...,...,...
96,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
97,2020-11-16,0:27:00,F9 B5B1061.1,KSC LC-39A,"Crew-1, Sentinel-6 Michael Freilich",12500,LEO (ISS),NASA (CCP),Success,Success
98,2020-11-21,17:17:08,F9 B5B1063.1,VAFB SLC-4E,"Sentinel-6 Michael Freilich, Starlink 15 v1.0",1192,LEO,NASA / NOAA / ESA / EUMETSAT,Success,Success
99,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success
100,2020-12-06,16:17:08,F9 B5 B1058.4,KSC LC-39A,SpaceX CRS-21,2972,LEO (ISS),NASA (CRS),Success,Success

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
   For Example "Landing_Outcome"**

### Task 1




##### Display the names of the unique launch sites  in the space mission

In [5]:
pd.read_sql("""
SELECT DISTINCT Launch_Site FROM SPACEXTBL;
""",conn)

    Launch_Site
0   CCAFS LC-40
1   VAFB SLC-4E
2    KSC LC-39A
3  CCAFS SLC-40


### Task 2


#####  Display 5 records where launch sites begin with the string 'CCA'

In [6]:
pd.read_sql("""
SELECT * FROM SPACEXTBL
WHERE Launch_Site LIKE "CCA%"
""",conn)

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
5,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170,GTO,SES,Success,No attempt
6,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325,GTO,Thaicom,Success,No attempt
7,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296,LEO (ISS),NASA (CRS),Success,Controlled (ocean)
8,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316,LEO,Orbcomm,Success,Controlled (ocean)
9,2014-08-05,8:00:00,F9 v1.1,CCAFS LC-40,AsiaSat 8,4535,GTO,AsiaSat,Success,No attempt
10,2014-09-07,5:00:00,F9 v1.1 B1011,CCAFS LC-40,AsiaSat 6,4428,GTO,AsiaSat,Success,No attempt
11,2014-09-21,5:52:00,F9 v1.1 B1010,CCAFS LC-40,SpaceX CRS-4,2216,LEO (ISS),NASA (CRS),Success,Uncontrolled (ocean)
12,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395,LEO (ISS),NASA (CRS),Success,Failure (drone ship)
13,2015-02-11,23:03:00,F9 v1.1 B1013,CCAFS LC-40,DSCOVR,570,HEO,U.S. Air Force NASA NOAA,Success,Controlled (ocean)
14,2015-03-02,3:50:00,F9 v1.1 B1014,CCAFS LC-40,ABS-3A Eutelsat 115 West B,4159,GTO,ABS Eutelsat,Success,No attempt
15,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898,LEO (ISS),NASA (CRS),Success,Failure (drone ship)
16,2015-04-27,23:03:00,F9 v1.1 B1016,CCAFS LC-40,Turkmen 52 / MonacoSAT,4707,GTO,Turkmenistan National Space Agency,Success,No attempt
17,2015-06-28,14:21:00,F9 v1.1 B1018,CCAFS LC-40,SpaceX CRS-7,1952,LEO (ISS),NASA (CRS),Failure (in flight),Precluded (drone ship)
18,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034,LEO,Orbcomm,Success,Success (ground pad)
19,2016-03-04,23:35:00,F9 FT B1020,CCAFS LC-40,SES-9,5271,GTO,SES,Success,Failure (drone ship)
20,2016-04-08,20:43:00,F9 FT B1021.1,CCAFS LC-40,SpaceX CRS-8,3136,LEO (ISS),NASA (CRS),Success,Success (drone ship)
21,2016-05-06,5:21:00,F9 FT B1022,CCAFS LC-40,JCSAT-14,4696,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
22,2016-05-27,21:39:00,F9 FT B1023.1,CCAFS LC-40,Thaicom 8,3100,GTO,Thaicom,Success,Success (drone ship)
23,2016-06-15,14:29:00,F9 FT B1024,CCAFS LC-40,ABS-2A Eutelsat 117 West B,3600,GTO,ABS Eutelsat,Success,Failure (drone ship)
24,2016-07-18,4:45:00,F9 FT B1025.1,CCAFS LC-40,SpaceX CRS-9,2257,LEO (ISS),NASA (CRS),Success,Success (ground pad)
25,2016-08-14,5:26:00,F9 FT B1026,CCAFS LC-40,JCSAT-16,4600,GTO,SKY Perfect JSAT Group,Success,Success (drone ship)
26,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205,LEO (ISS),NASA (CRS),Success,Success (ground pad)
27,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,5000,LEO,Northrop Grumman,Success (payload status unclear),Success (ground pad)
28,2018-01-31,21:25:00,F9 FT B1032.2,CCAFS SLC-40,GovSat-1 / SES-16,4230,GTO,SES,Success,Controlled (ocean)
29,2018-03-06,5:33:00,F9 B4 B1044,CCAFS SLC-40,Hispasat 30W-6 PODSat,6092,GTO,Hispasat NovaWurks,Success,No attempt
30,2018-04-02,20:30:00,F9 B4 B1039.2,CCAFS SLC-40,SpaceX CRS-14,2647,LEO (ISS),NASA (CRS),Success,No attempt
31,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362,HEO,NASA (LSP),Success,Success (drone ship)
32,2018-06-04,4:45:00,F9 B4 B1040.2,CCAFS SLC-40,SES-12,5384,GTO,SES,Success,No attempt
33,2018-06-29,9:42:00,F9 B4 B1045.2,CCAFS SLC-40,SpaceX CRS-15,2697,LEO (ISS),NASA (CRS),Success,No attempt
34,2018-07-22,5:50:00,F9 B5B1047.1,CCAFS SLC-40,Telstar 19V,7075,GTO,Telesat,Success,Success
35,2018-08-07,5:18:00,F9 B5 B1046.2,CCAFS SLC-40,Merah Putih,5800,GTO,Telkom Indonesia,Success,Success
36,2018-09-10,4:45:00,F9 B5B1049.1,CCAFS SLC-40,Telstar 18V / Apstar-5C,7060,GTO,Telesat,Success,Success
37,2018-12-05,18:16:00,F9 B5B1050,CCAFS SLC-40,SpaceX CRS-16,2500,LEO (ISS),NASA (CRS),Success,Failure
38,2018-12-23,13:51:00,F9 B5B1054,CCAFS SLC-40,GPS III-01,4400,MEO,USAF,Success,No attempt
39,2019-02-22,1:45:00,F9 B5 B1048.3,CCAFS SLC-40,"Nusantara Satu, Beresheet Moon lander, S5",4850,GTO,"PSN, SpaceIL / IAI",Success,Success
40,2019-05-04,6:48:00,F9 B5B1056.1,CCAFS SLC-40,"SpaceX CRS-17, Starlink v0.9",2495,LEO (ISS),NASA (CRS),Success,Success
41,2019-05-24,2:30:00,F9 B5 B1049.3,CCAFS SLC-40,"Starlink v0.9, RADARSAT Constellation",13620,LEO,SpaceX,Success,Success
42,2019-07-25,22:01:00,F9 B5 B1056.2,CCAFS SLC-40,"SpaceX CRS-18, AMOS-17",2268,LEO (ISS),NASA (CRS),Success,Success
43,2019-08-06,23:23:00,F9 B5 B1047.3,CCAFS SLC-40,"AMOS-17, Starlink 1 v1.0",6500,GTO,Spacecom,Success,No attempt
44,2019-11-11,14:56:00,F9 B5 B1048.4,CCAFS SLC-40,"Starlink 1 v1.0, SpaceX CRS-19",15600,LEO,SpaceX,Success,Success
45,2019-12-05,17:29:00,F9 B5B1059.1,CCAFS SLC-40,"SpaceX CRS-19, JCSat-18 / Kacific 1",2617,LEO (ISS),"NASA (CRS), Kacific 1",Success,Success
46,2019-12-17,0:10:00,F9 B5 B1056.3,CCAFS SLC-40,"JCSat-18 / Kacific 1, Starlink 2 v1.0",6956,GTO,"Sky Perfect JSAT, Kacific 1",Success,Success
47,2020-01-07,2:33:00,F9 B5 B1049.4,CCAFS SLC-40,"Starlink 2 v1.0, Crew Dragon in-flight abort t...",15600,LEO,SpaceX,Success,Success
48,2020-01-29,14:07:00,F9 B5 B1051.3,CCAFS SLC-40,"Starlink 3 v1.0, Starlink 4 v1.0",15600,LEO,SpaceX,Success,Success
49,2020-02-17,15:05:00,F9 B5 B1056.4,CCAFS SLC-40,"Starlink 4 v1.0, SpaceX CRS-20",15600,LEO,SpaceX,Success,Failure
50,2020-03-07,4:50:00,F9 B5 B1059.2,CCAFS SLC-40,"SpaceX CRS-20, Starlink 5 v1.0",1977,LEO (ISS),NASA (CRS),Success,Success
51,2020-06-04,1:25:00,F9 B5 B1049.5,CCAFS SLC-40,"Starlink 7 v1.0, Starlink 8 v1.0",15600,LEO,"SpaceX, Planet Labs",Success,Success
52,2020-06-13,9:21:00,F9 B5 B1059.3,CCAFS SLC-40,"Starlink 8 v1.0, SkySats-16, -17, -18, GPS III...",15410,LEO,"SpaceX, Planet Labs",Success,Success
53,2020-06-30,20:10:46,F9 B5B1060.1,CCAFS SLC-40,"GPS III-03, ANASIS-II",4311,MEO,U.S. Space Force,Success,Success
54,2020-07-20,21:30:00,F9 B5 B1058.2,CCAFS SLC-40,"ANASIS-II, Starlink 9 v1.0",5500,GTO,"Republic of Korea Army, Spaceflight Industries...",Success,Success
55,2020-08-18,14:31:00,F9 B5 B1049.6,CCAFS SLC-40,"Starlink 10 v1.0, SkySat-19, -20, -21, SAOCOM 1B",15440,LEO,"SpaceX, Planet Labs, PlanetIQ",Success,Success
56,2020-08-30,23:18:00,F9 B5 B1059.4,CCAFS SLC-40,"SAOCOM 1B, GNOMES 1, Tyvak-0172",3130,SSO,"CONAE, PlanetIQ, SpaceX",Success,Success
57,2020-10-24,15:31:34,F9 B5 B1060.3,CCAFS SLC-40,"Starlink 14 v1.0, GPS III-04",15600,LEO,SpaceX,Success,Success
58,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
59,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success

### Task 3




##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [7]:
pd.read_sql("""
SELECT SUM(PAYLOAD_MASS__KG_) AS TOTAL_PAYLOAD_MASS FROM SPACEXTBL
WHERE Customer = "NASA (CRS)";
""",conn)

   TOTAL_PAYLOAD_MASS
0               45596

### Task 4




##### Display average payload mass carried by booster version F9 v1.1

In [8]:
pd.read_sql("""
SELECT AVG(PAYLOAD_MASS__KG_) AS AVERAGE_PAYLOAD_MASS FROM SPACEXTBL
WHERE Booster_Version = "F9 v1.1";
""",conn)

   AVERAGE_PAYLOAD_MASS
0                2928.4

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.


_Hint:Use min function_

In [9]:
pd.read_sql("""
SELECT MIN(DATE) AS FIRST_SUCCESFUL_LANDING FROM SPACEXTBL
WHERE Landing_Outcome = "Success (ground pad)";
""",conn)

  FIRST_SUCCESFUL_LANDING
0              2015-12-22

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [10]:
pd.read_sql("""
SELECT DISTINCT Booster_Version FROM SPACEXTBL
WHERE Landing_Outcome = "Success (drone ship)"
AND Payload_Mass__kg_ > 4000
AND Payload_Mass__kg_ < 6000; 
""",conn)

  Booster_Version
0     F9 FT B1022
1     F9 FT B1026
2  F9 FT  B1021.2
3  F9 FT  B1031.2

### Task 7




##### List the total number of successful and failure mission outcomes

In [11]:
pd.read_sql("""
SELECT Mission_Outcome, COUNT(*) AS Total
FROM SPACEXTBL
GROUP BY Mission_Outcome;
""",conn)

                    Mission_Outcome  Total
0               Failure (in flight)      1
1                           Success     98
2                          Success       1
3  Success (payload status unclear)      1

### Task 8



##### List all the booster_versions that have carried the maximum payload mass, using a subquery with a suitable aggregate function.

In [12]:
pd.read_sql("""
SELECT Booster_Version
FROM SPACEXTBL
WHERE Payload_Mass__KG_ = (
    SELECT MAX(Payload_Mass__KG_)
    FROM SPACEXTBL
);
""",conn)

   Booster_Version
0    F9 B5 B1048.4
1    F9 B5 B1049.4
2    F9 B5 B1051.3
3    F9 B5 B1056.4
4    F9 B5 B1048.5
5    F9 B5 B1051.4
6    F9 B5 B1049.5
7   F9 B5 B1060.2
8   F9 B5 B1058.3
9    F9 B5 B1051.6
10   F9 B5 B1060.3
11  F9 B5 B1049.7

### Task 9


##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use  substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [13]:
pd.read_sql("""
SELECT 
    substr(Date, 6, 2) AS Month,
    Landing_Outcome,
    Booster_Version,
    Launch_Site
FROM SPACEXTBL
WHERE substr(Date, 0, 5) = '2015'
AND Landing_Outcome = 'Failure (drone ship)';
""", conn)

  Month       Landing_Outcome Booster_Version  Launch_Site
0    01  Failure (drone ship)   F9 v1.1 B1012  CCAFS LC-40
1    04  Failure (drone ship)   F9 v1.1 B1015  CCAFS LC-40

### Task 10




##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

In [14]:
pd.read_sql("""
SELECT 
    Landing_Outcome,
    COUNT(*) AS Count
FROM SPACEXTBL
WHERE Date BETWEEN '2010-06-04' AND '2017-03-20'
GROUP BY Landing_Outcome
ORDER BY Count DESC;
""", conn)

          Landing_Outcome  Count
0              No attempt     10
1    Success (drone ship)      5
2    Failure (drone ship)      5
3    Success (ground pad)      3
4      Controlled (ocean)      3
5    Uncontrolled (ocean)      2
6     Failure (parachute)      2
7  Precluded (drone ship)      1